### ISSUE TITLE
Box : Catalogue

### ISSUE THREAD

**Issue by AlessGarau** [openbox-dev/openbox-server#33]

**Comment by LTOssian** [comment]
## TODO :

**Mise en place le Layout des catalogues dans _catalog.tsx avec CatalogLayout**
_voir figma_
- [ ] Le Header
- [ ] Le h1 avec le nom du catalogue
- [ ] La SideBar des filtres
- [ ] La Barre des filtres quand il y en a

**Création du composant BoxCard dans ui/common**
- [ ] Utiliser les bons props et créer l'interface correspondante
- [ ] Création d'un fichier scss réutilisable car BoxCard apparait dans d'autres pages 

**Utilisation d'un Loader dans BoxCatalog**
- [ ] Créer les services figma nécessaires
- [ ] Créer le loader et renvoyer une réponse formatée pour l'exploiter facilement
- [ ] Mapping des résultats du Loader dans BoxCatalog pour créer les BoxCard
