### ISSUE TITLE
Page: Box

### ISSUE THREAD

**Issue by LTOssian** [openbox-dev/openbox-server#44]
## Tasks

- [ ] Créer un loader prenant en compte le paramètre boxId dans l'url afin de charger les données de la bonne box
- [ ] Réaliser un frontend respectant la maquette
- [ ] Assurer la vue mobile
- [ ] Utiliser les composants EventCard ainsi que le mixant eventCardMixin dans le scss, en mettant la classe two-column-grid
